server:
  servlet:
    context-path: /ci/
    session:
      cookie:
        name: ci
        path: /
      timeout: 1h

  port: 8080
  tomcat.uri-encoding: UTF-8
spring:
  profiles:
    active: localhost
  redis:
    #    cluster:
    #      max-redirects: 3
    #      nodes: 103.97.33.170:6379
    host: 103.97.33.170
    database: 1
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 1000ms
    timeout: 5000ms
    #    password: N9c3j8a7L3e2i0f2E3
    password: c8z8hXuSI87jYzzK

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    write:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://103.51.12.156:3306/cims?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: writer
      password: h4B3e2u6H2#3d8F6
    read:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://103.51.12.157:3306/cims?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: reader
      password: n7v#A3u2j4d5F3D6


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+7

# MyBatis
mybatis:
  typeAliasesPackage: com.cims.business.**.entity
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

#logger
logging:
  file: logs/ci.log
  level:
    root: info
    com.cims.business: debug


---
spring:
  profiles: dev
server:
  port: 8080
---
spring:
  profiles: prod
server:
  port: 8080
---
spring:
  profiles: prod2
server:
  port: 8081

